CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  user_role ENUM('admin', 'manager', 'user') NOT NULL DEFAULT 'user',
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
  admin_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  admin_level VARCHAR(50) NOT NULL DEFAULT 'standard',
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_admins_user
    FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS foods (
  food_id INT AUTO_INCREMENT PRIMARY KEY,
  food_name VARCHAR(150) NOT NULL UNIQUE,
  calories_per_100g DECIMAL(10, 1) NOT NULL DEFAULT 0,
  protein_per_100g DECIMAL(10, 1) NOT NULL DEFAULT 0,
  carbs_per_100g DECIMAL(10, 1) NOT NULL DEFAULT 0,
  fat_per_100g DECIMAL(10, 1) NOT NULL DEFAULT 0,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meals (
  meal_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  meal_name VARCHAR(150) NOT NULL,
  meal_date DATE NOT NULL,
  image_path VARCHAR(255) NULL,
  total_calories DECIMAL(10, 1) NOT NULL DEFAULT 0,
  total_protein DECIMAL(10, 1) NOT NULL DEFAULT 0,
  total_carbs DECIMAL(10, 1) NOT NULL DEFAULT 0,
  total_fat DECIMAL(10, 1) NOT NULL DEFAULT 0,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_meals_user_date (user_id, meal_date),
  CONSTRAINT fk_meals_user
    FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS meal_items (
  meal_item_id INT AUTO_INCREMENT PRIMARY KEY,
  meal_id INT NOT NULL,
  food_id INT NOT NULL,
  confirmed_portion_grams DECIMAL(10, 1) NOT NULL,
  calories DECIMAL(10, 1) NOT NULL DEFAULT 0,
  protein DECIMAL(10, 1) NOT NULL DEFAULT 0,
  carbs DECIMAL(10, 1) NOT NULL DEFAULT 0,
  fat DECIMAL(10, 1) NOT NULL DEFAULT 0,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_meal_items_meal (meal_id),
  INDEX idx_meal_items_food (food_id),
  CONSTRAINT fk_meal_items_meal
    FOREIGN KEY (meal_id) REFERENCES meals(meal_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_meal_items_food
    FOREIGN KEY (food_id) REFERENCES foods(food_id)
    ON DELETE RESTRICT
);
