CREATE TABLE IF NOT EXISTS user_settings (
  setting_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  username VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  theme ENUM('light', 'dark') NOT NULL DEFAULT 'light',
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_settings_user
    FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON DELETE CASCADE
);
